#@data/values
#! https://github.com/k14s/ytt/blob/master/examples/data-values/values.yml
#! If necessary, these values can be overwritten in a number of ways: https://github.com/k14s/ytt/blob/master/docs/ytt-data-values.md
---
dns:
  record_owner: linode-kubernetes-engine
  log_level: debug #! info is the default, but we want to know more...
#! provided just-in-time
image:
namespace:
